### ISSUE TITLE
About Getting Started

### ISSUE THREAD

**Issue by JunkunPeng17** [mihirp1998/Diffusion-TTA#3]
Hi, thanks for your good work and sharing the code. I'm trying to do some experiments based on your model but have met some problems. I carefully followed your training environment, and when I used the command to run the code, I got this error:
![error](https://github.com/mihirp1998/Diffusion-TTA/assets/56396894/4d374663-db90-45b3-bb55-56f4e87e4eaa)
Could you give me some advice about how to fix the problem?

**Comment by buttomnutstoast** [comment]
Hi, thanks for your interest in our code.  What's the command you were using?

Also, did you use this [DiT](https://github.com/mihirp1998/DiT.git) repo instead of the official one?  The official DiT repo does not support conditioning with the predicted classification.

**Comment by JunkunPeng17** [comment]
Thanks for your quick reply. I just followed your guide to clone your DiT branch from the official repo. The command I use is ConvNext-Large/DiT. I also tested other commands like ConvNext-Tiny/DiT (single-sample TTA on ImageNet-R or -C-A), and it faced the same error.

**Comment by buttomnutstoast** [comment]
Hi,  the input tensor shape doesn't look correct to me.  The `class_text_embeddings` variable [here](https://github.com/mihirp1998/Diffusion-TTA/blob/468fbb4b5fc0cd18ac2693f49dc6eed653b1c2dd/diff_tta/models/tta.py#L224-L226) should be a tensor of shape `(1, 1000, 1152)` and the `probs` variable [here](https://github.com/mihirp1998/Diffusion-TTA/blob/468fbb4b5fc0cd18ac2693f49dc6eed653b1c2dd/diff_tta/models/tta.py#L223) should be a tensor of shape `(1, 1000, 1)`.  To guide the classifier, we weighted average `class_text_embeddings` with the classification `probs`, resulting in the variable `context` of shape `(1, 1152)`.

Did you modify the code? If so, could you show the change of codes?  Also, could you print out the tensor shape in each line of this [code block](https://github.com/mihirp1998/Diffusion-TTA/blob/468fbb4b5fc0cd18ac2693f49dc6eed653b1c2dd/diff_tta/models/tta.py#L221-L233)?

**Comment by JunkunPeng17** [comment]
Thanks for your reply! Based on your feedback, I fixed the error. It is really a small mistake when I change the codes and forget to delete one of lines. Thus, the wrong code changes the tensor shape.
