### ISSUE TITLE
Estimated training time

### ISSUE THREAD

**Issue by JiayiGuo821** [mihirp1998/Diffusion-TTA#9]
Thanks for sharing the code! Wonderful work!

I'm curious about the training time. I tried to reproduce the ConvNext-Large experiments on ImageNet-C and found that it took about 43 seconds for a single sample on an A100. Thus it may require about 25 GPU days to go through 50000 images. Is that expected?

**Comment by mihirp1998** [comment]
Yes with our current implementation. Although using recent fast samplers
(like DPM) and even one-step diffusion models should significantly increase
the speed.

**Comment by JiayiGuo821** [comment]
Thanks for the prompt reply!
In your experiments, did you train diffusion-tta with a single GPU and wait 25 days? Or there are some ways to accelerate the training. 
I'm considering using multiple GPUs, but seems like that will conflict with the definition of "online" training.

**Comment by mihirp1998** [comment]
We subsampled the test set to 5 examples per class while reporting the resuts as we report in the paper. This is similar to https://arxiv.org/abs/2303.16203

**Comment by JiayiGuo821** [comment]
Get! Thank you so much!
